## PyTorch fundamentals

In [1]:
import torch
print(torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

/Users/mhars/miniforge3/envs/spyder-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


1.13.1


# Introduction to tensor

# Creating scaler

In [2]:
# scalar
scalar = torch.tensor(6)
scalar


tensor(6)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

6

In [5]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7,8],
                            [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                                [3,6,9],
                                [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [17]:
# Create a random tensor of size / shape
random_tensor = torch.rand(3,4)
random_tensor

tensor([[7.5836e-01, 5.2314e-01, 1.5871e-01, 1.7546e-01],
        [7.4521e-01, 9.5311e-01, 7.5192e-01, 9.4695e-02],
        [8.7965e-01, 7.9053e-01, 5.5745e-01, 8.7136e-04]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similiar size to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3)) # height , width & color channels
random_image_size_tensor.ndim,random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors

In [23]:
one_ten = torch.arange(1,11)
one_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating a tensors like
ten_zeros = torch.zeros_like(input=one_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensors Datatypes

In [25]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                            dtype=None, # What datatype is the tensor
                                            device=None, # What device your tensor is on
                                            requires_grad=False) # Whether or not to track gradients 
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor,float_32_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float32)

## Getting information from tensor




1. Tensor not right datatype -to do get datatype from a tensor ,can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on right device - to get device from a tensor,can use tensor.device

In [28]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor


tensor([[0.4443, 0.9997, 0.3000, 0.9747],
        [0.3247, 0.4699, 0.6086, 0.1757],
        [0.9103, 0.4231, 0.4172, 0.9349]])

In [29]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor:{some_tensor.dtype}')
print(f'Shape of tensor:{some_tensor.size()}')
print(f'Device tensor is on:{some_tensor.device}')
print(f'')


tensor([[0.4443, 0.9997, 0.3000, 0.9747],
        [0.3247, 0.4699, 0.6086, 0.1757],
        [0.9103, 0.4231, 0.4172, 0.9349]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu



### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [30]:
# create a tensor and add 10
tensor = torch.tensor([1,2,3])
tensor+10


tensor([11, 12, 13])

In [31]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [32]:
# Subtract tensor by 10
tensor-10

tensor([-9, -8, -7])

In [33]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [34]:
torch.add(tensor,10)

tensor([11, 12, 13])

## Matrix multiplication

Two main ways of performing multiplication in nueral networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [35]:
# Element wise multipilication
print(tensor,'*',tensor)
print(f'Equals: {tensor*tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [36]:
# Matrix multipilication

torch.matmul(tensor,tensor)

tensor(14)

In [37]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 502 µs, sys: 450 µs, total: 952 µs
Wall time: 627 µs


In [38]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 25 µs, sys: 1e+03 ns, total: 26 µs
Wall time: 27.9 µs


tensor(14)

### One of the most common errors in nueral networks and deep learning: Shape errors



In [39]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [40]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

 To fix our tensor shape issues, we can manipulate the shape of one out tensors using a transpose
 A transpose switches the axes or dimensions of a given tensor

In [41]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [42]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Finding the min,max,mean & sum etc (tensor aggregation)

In [43]:
x  = torch.arange(0,100,10)
x,x.shape

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]))

In [44]:
torch.min(x),x.min

(tensor(0), <function Tensor.min>)

In [45]:
torch.max(x),x.min

(tensor(90), <function Tensor.min>)

In [46]:
torch.mean(x.type(torch.float16)),x.type(torch.float64).mean()

(tensor(45., dtype=torch.float16), tensor(45., dtype=torch.float64))

In [47]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [48]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
x.argmin()

tensor(0)

In [50]:
x.argmax()

tensor(9)

## Reshaping, stacking,squeezing and unsqueezing tensors

In [51]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [53]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [55]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [56]:
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [57]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
x_squeezed = x_reshaped.squeeze()
x_squeezed.shape

torch.Size([9])

In [59]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed,x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order

x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2,0,1)

x_original.shape,x_permuted.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# Indexing (selecting data from tensors)

In [61]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [62]:
# Let's index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
x[0][0]

tensor([1, 2, 3])

In [64]:
x[0][0][0]

tensor(1)

In [65]:
x[0][1][1]

tensor(5)

In [66]:
x[:,2]

tensor([[7, 8, 9]])

In [67]:
x[:,:,1]

tensor([[2, 5, 8]])

In [68]:
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [69]:
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [70]:
torch.arange(1.0,8.0).dtype

torch.float32

# Reproducbility

In [71]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.6551, 0.3962, 0.6771, 0.4001],
        [0.0439, 0.8088, 0.7103, 0.2361],
        [0.9311, 0.8680, 0.7804, 0.3415]])
tensor([[0.5155, 0.8603, 0.6588, 0.5046],
        [0.5511, 0.7021, 0.5758, 0.8831],
        [0.3677, 0.6291, 0.7519, 0.6168]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [72]:
random_seed = 42

torch.manual_seed(random_seed)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(random_seed)

random_tensor_D = torch.rand(3,4)


print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and pytorch objects on the GPUs (and making faster )



1. Getting GPU

In [73]:
import torch
torch.cuda.is_available()

False

In [74]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'